services:
  normal_node:
    container_name: normal_node
    image: "vcity/validator"
    environment:
      - MONIKER=normal_node
    volumes:
      - ../public/node_files:/app/node_files
      - ./normal_node:/home/user/.vcity
    command: 
      - cp /app/node_files/* /home/user/ && cp /app/node_files/.env /home/user/ && cp /home/user/bin/* /home/user/ && chmod +x ./start-node.sh && ./start-node.sh normal_node
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5