services:

  first_node:
    container_name: first_node
    image: "vcity/validator"
    environment:
      - MONIKER=first_node
    volumes:
      - ../public/node_files:/app/node_files
      - ./first_node:/home/user/.vcity
      # - ../public/bin/:/home/user/bin
    command: 
      - cp /app/node_files/* /home/user/ && cp /app/node_files/.env /home/user/ && cp /home/user/bin/* /home/user/ && chmod +x ./start-node.sh && ./start-node.sh first_node
      # - cp /app/node_files/* /home/user/ && cp /app/node_files/.env /home/user/ && cp /home/user/bin/* /home/user/ && tail -f /dev/null
      # - tail -f /dev/null
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "26656-26657:26656-26657"
      - "8545:8545"
      - "1317:1317"
    
  validator_node:
    container_name: validator_node
    image: "vcity/validator"
    environment:
      - MONIKER=validator_node
    volumes:
      - ../public/node_files:/app/node_files
      - ./validator_node:/home/user/.vcity
      # - ../public/bin/:/home/user/bin
    command:
      - cp /app/node_files/* /home/user/ && cp /app/node_files/.env /home/user/ && cp /home/user/bin/* /home/user/ && chmod +x ./*.sh && ./start-node.sh validator_node
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "26659-26660:26656-26657"
      - "8546:8545"
      - "1318:1317"

  validator_node_2:
    container_name: validator_node_2
    image: "vcity/validator"
    environment:
      - MONIKER=validator_node_2
    volumes:
      - ../public/node_files:/app/node_files
      - ./validator_node_2:/home/user/.vcity
      # - ../public/bin/:/home/user/bin
    command:
      - cp /app/node_files/* /home/user/ && cp /app/node_files/.env /home/user/ && cp /home/user/bin/* /home/user/ && chmod +x ./*.sh && ./start-node.sh validator_node
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "26662-26663:26656-26657"
      - "8547:8545"
      - "1319:1317"

  snap_node:
    container_name: snap_node
    image: "vcity/validator"
    environment:
      - MONIKER=snap_node
    volumes:
      - ../public/node_files:/app/node_files
      - ./snap_node:/home/user/.vcity
      # - ../public/bin/:/home/user/bin
    command:
      - cp /app/node_files/* /home/user/ && cp /app/node_files/.env /home/user/ && cp /home/user/bin/* /home/user/ && chmod +x ./*.sh && ./start-node.sh snap_node
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "26665-26666:26656-26657"
      - "8548:8545"
      - "1320:1317"

  seed_node:
    container_name: seed_node
    image: "vcity/validator"
    environment:
      - MONIKER=seed_node
    volumes:
      - ../public/node_files:/app/node_files
      - ./seed_node:/home/user/.vcity
      # - ../public/bin/:/home/user/bin
    command:
      - cp /app/node_files/* /home/user/ && cp /app/node_files/.env /home/user/ && cp /home/user/bin/* /home/user/ && chmod +x ./*.sh && ./start-node.sh seed_node
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "26668-26669:26656-26657"
      - "8549:8545"
      - "1321:1317"

  normal_node:
    container_name: normal_node
    image: "vcity/validator"
    environment:
      - MONIKER=normal_node
    volumes:
      - ../public/node_files:/app/node_files
      - ./normal_node:/home/user/.vcity
    command: 
      - cp /app/node_files/* /home/user/ && cp /app/node_files/.env /home/user/ && cp /home/user/bin/* /home/user/ && chmod +x ./start-node.sh && ./start-node.sh normal_node
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "26671-26672:26656-26657"
      - "8550:8545"
      - "1322:1317"